theme: cayman
title: Neural Motifs: Scene Graph Parsing with Global Context
description: Project page for Neural Motifs (Zellers et al. CVPR 2018)
show_downloads: "false"
google_analytics: UA-84290243-3
